package io.velora.api.compiler;

/**
 * Stable diagnostic codes used across the compiler pipeline.
 *
 * <p>Format: {@code VLS-<STAGE>-<NNNN>}.
 */
public enum DiagnosticCode {
    // Lexer
    LEXER_UNTERMINATED_STRING("VLS-LEX-0001"),
    LEXER_INVALID_NUMBER("VLS-LEX-0002"),
    LEXER_UNEXPECTED_CHAR("VLS-LEX-0003"),

    // Parser
    PARSER_UNEXPECTED_TOKEN("VLS-PAR-0001"),
    PARSER_MISSING_TOKEN("VLS-PAR-0002"),
    PARSER_INVALID_SETTING_DECL("VLS-PAR-0003"),

    // Settings
    SETTING_DUPLICATE_ID("VLS-SETTING-0001"),
    SETTING_UNKNOWN_ANNOTATION("VLS-SETTING-0002"),
    SETTING_INVALID_DEFAULT("VLS-SETTING-0003"),
    SETTING_OUT_OF_RANGE("VLS-SETTING-0004"),
    SETTING_INVALID_STEP("VLS-SETTING-0005"),
    SETTING_CONDITION_NOT_BOOLEAN("VLS-SETTING-0006"),
    SETTING_UNKNOWN_REFERENCE("VLS-SETTING-0007"),
    SETTING_CYCLIC_DEPENDENCY("VLS-SETTING-0008"),
    SETTING_READONLY("VLS-SETTING-0009"),
    SETTING_REDECLARED("VLS-SETTING-0010"),

    // Semantic / types
    SEMANTIC_UNRESOLVED_SYMBOL("VLS-SEM-0001"),
    SEMANTIC_TYPE_MISMATCH("VLS-SEM-0002"),
    SEMANTIC_NULLABILITY("VLS-SEM-0003"),
    SEMANTIC_AMBIGUOUS_OVERLOAD("VLS-SEM-0004"),
    SEMANTIC_DIVISION_BY_ZERO("VLS-SEM-0005"),
    SEMANTIC_INVALID_ARGUMENT("VLS-SEM-0006"),
    SEMANTIC_PERMISSION_EXCEEDED("VLS-SEM-0007"),
    SEMANTIC_IMPORT_CYCLE("VLS-SEM-0008"),
    SEMANTIC_DUPLICATE_SYMBOL("VLS-SEM-0009"),
    SEMANTIC_MISSING_INITIALIZER("VLS-SEM-0010"),
    SEMANTIC_MISSING_RETURN("VLS-SEM-0011"),
    SEMANTIC_CONST_ASSIGNMENT("VLS-SEM-0012"),
    SEMANTIC_SETTING_READONLY("VLS-SEM-0013"),
    SEMANTIC_PRIMITIVE_NULL("VLS-SEM-0014"),
    SEMANTIC_ASYNC_VIOLATION("VLS-SEM-0015"),
    SEMANTIC_UNTYPED_DECLARATION("VLS-SEM-0016"),
    SEMANTIC_STATIC_CONST_CONFLICT("VLS-SEM-0017"),
    SEMANTIC_CONST_RUNTIME_INIT("VLS-SEM-0018"),
    SEMANTIC_DEFAULT_BEFORE_REQUIRED("VLS-SEM-0019"),
    SEMANTIC_WRONG_RETURN_TYPE("VLS-SEM-0020"),
    SEMANTIC_VOID_RETURN_VALUE("VLS-SEM-0021"),
    SEMANTIC_WRONG_ARITY("VLS-SEM-0022"),
    SEMANTIC_WRONG_ARG_TYPE("VLS-SEM-0023"),
    SEMANTIC_NON_BOOLEAN_CONDITION("VLS-SEM-0024"),
    SEMANTIC_NON_ITERABLE("VLS-SEM-0025"),
    SEMANTIC_UNKNOWN_PERMISSION("VLS-SEM-0026"),
    SEMANTIC_UNKNOWN_ANNOTATION("VLS-SEM-0027"),
    SEMANTIC_SETTING_WRITE("VLS-SEM-0028"),
    SEMANTIC_NAMED_ARG_UNKNOWN("VLS-SEM-0029"),
    SEMANTIC_NAMED_ARG_DUPLICATE("VLS-SEM-0030"),
    SEMANTIC_INDEX_TYPE_MISMATCH("VLS-SEM-0031"),
    SEMANTIC_INVALID_ASSIGNMENT_TARGET("VLS-SEM-0032"),
    SEMANTIC_NON_CONSTANT_FIELD_INIT("VLS-SEM-0033"),
    SEMANTIC_INVALID_PERSISTENT_TYPE("VLS-SEM-0034"),

    // Compiler
    COMPILER_UNSUPPORTED_VERSION("VLS-CMP-0001"),
    COMPILER_CACHE_MISS("VLS-CMP-0002"),
    COMPILER_PATH_TRAVERSAL("VLS-CMP-0003"),
    COMPILER_MULTIPLE_SCRIPTS("VLS-CMP-0004"),
    COMPILER_NO_SCRIPT("VLS-CMP-0005"),

    // Bytecode / verifier
    BYTECODE_INVALID_OPCODE("VLS-BC-0001"),
    BYTECODE_BAD_OPERAND("VLS-BC-0002"),
    BYTECODE_BAD_JUMP("VLS-BC-0003"),
    BYTECODE_STACK_MISMATCH("VLS-BC-0004"),
    BYTECODE_STORE_SETTING("VLS-BC-0005"),

    // Runtime
    RUNTIME_RESOURCE_LIMIT("VLS-RT-0001"),
    RUNTIME_INVALID_HANDLE("VLS-RT-0002"),
    RUNTIME_API_ERROR("VLS-RT-0003"),
    RUNTIME_DIVISION_BY_ZERO("VLS-RT-0004"),
    RUNTIME_ARITHMETIC_OVERFLOW("VLS-RT-0005"),
    RUNTIME_INDEX_OUT_OF_BOUNDS("VLS-RT-0006");

    private final String code;

    DiagnosticCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
